apiVersion: v1
kind: Service
metadata:
  labels:
    component: anycable-rpc
  name: anycable-rpc-svc
  namespace: default
spec:
  ports:
    - name: http
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    component: anycable-rpc
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: anycable-rpc
  name: anycable-rpc
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: anycable-rpc
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: anycable-rpc
    spec:
      containers:
      - command:
        - bundle
        - exec
        - anycable
        - --rpc-host=0.0.0.0:50051
        env:
        - name: RAILS_ENV
          value:  ${CHANGE_ME}
        - name: PASSENGER_APP_ENV
          value:  ${CHANGE_ME}
        - name: WEB_SERVER
          value: "1"
        - name: DD_TRACE_STARTUP_LOGS
          value: "1"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "1"
        - name: DONT_USE_VIRTUAL
          value: "1"
        envFrom:
        - configMapRef:
            name: ${CHANGE_ME} #chowly-prod-env
        image: ${CHANGE_ME} #chowly/web:2022-07-01-1656713335
        imagePullPolicy: IfNotPresent
        name: anycable-rpc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30